"use client";

import { useEffect, useState } from "react";
import {
  Activity, AlertTriangle, ArrowLeft, ArrowRight, ArrowUpRight,
  CheckCircle2, ChevronRight, CircleDollarSign,
  Cpu, Database, Eye, Gauge, History,
  LockKeyhole, Pause, Play, Plus, Search,
  ShieldCheck, UserRoundCheck,
} from "lucide-react";
import { Area, AreaChart, CartesianGrid, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { navigation } from "./console/config";
import { ConsoleToolbar } from "./console/console-toolbar";
import { getConsoleCopy, getViewTitle } from "./console/i18n";
import { canAccessView, firstAllowedView, permissions } from "./console/permissions";
import type { ConsoleTheme, Locale, Role, RunState, View } from "./console/types";
import { ExperimentBuilder } from "./console/views/experiment-builder";
import { InteractiveBackground } from "./interactive-background";
const robustness = [
  { severity: "Clean", map: 72.8, retention: 100 }, { severity: "S1", map: 68.4, retention: 94 },
  { severity: "S2", map: 61.9, retention: 85 }, { severity: "S3", map: 52.6, retention: 72 },
  { severity: "S4", map: 40.2, retention: 55 }, { severity: "S5", map: 27.3, retention: 38 },
];
const corruptionRows = [
  ["Gaussian noise",67,58,45,31,19],["Shot noise",68,60,48,35,22],["Impulse noise",66,55,41,28,16],
  ["Defocus blur",70,65,57,47,35],["Glass blur",65,53,39,25,14],["Motion blur",69,61,51,39,27],
  ["Zoom blur",70,63,54,44,32],["Snow",68,57,43,29,17],["Frost",67,56,42,30,18],
  ["Fog",71,66,56,43,28],["Brightness",72,69,65,59,51],["Contrast",70,61,49,35,23],
  ["Elastic",69,62,54,45,36],["Pixelate",71,67,61,53,44],["JPEG",72,69,65,60,53],
] as const;
const initialCases = [
  { id:"FC-038", sample:"KITTI-007481", attack:"Snow / S4", issue:"Pedestrian disappearance", severity:"Critical", status:"Open" },
  { id:"FC-037", sample:"KITTI-003912", attack:"PGD / 8-255", issue:"Car → Cyclist flip", severity:"High", status:"Open" },
  { id:"FC-036", sample:"KITTI-006120", attack:"Fog / S5", issue:"False negative cluster", severity:"High", status:"Review" },
  { id:"FC-035", sample:"COCO-184771", attack:"Patch / 12%", issue:"Confidence collapse", severity:"Medium", status:"Mitigated" },
];
const experimentRows = [
  { name:"KITTI / YOLOv8n / Weather suite", status:"Đang chạy", progress:68, delta:"-19.4 mAP", tone:"cyan" },
  { name:"COCO / YOLOv8m / PGD sweep", status:"Cần review", progress:100, delta:"41.2% ASR", tone:"orange" },
  { name:"nuScenes / YOLOv8n / Sensor blur", status:"Hoàn tất", progress:100, delta:"83% rPC", tone:"green" },
];

function MetricCard({label,value,detail,tone}:{label:string;value:string;detail:string;tone:string}) {
  return <article className="metric-card"><div className="metric-card__head"><span>{label}</span><i className={`status-dot status-dot--${tone}`} /></div><strong>{value}</strong><p>{detail}</p></article>;
}
function SectionTitle({index,title,detail,action}:{index:string;title:string;detail?:string;action?:React.ReactNode}) {
  return <div className="section-title"><div><span className="section-index">{index}</span><h2>{title}</h2></div>{action ?? <p>{detail}</p>}</div>;
}

export function AdverTestApp() {
  const [view,setView] = useState<View>("dashboard");
  const [role,setRole] = useState<Role>("Safety Reviewer");
  const [locale,setLocale] = useState<Locale>("vi");
  const [theme,setTheme] = useState<ConsoleTheme>("dark");
  const [mobileReadOnly,setMobileReadOnly] = useState(false);
  const [run,setRun] = useState<RunState>({progress:68,status:"running",cost:18.42,cached:1240});
  const [reportStatus,setReportStatus] = useState<"DRAFT"|"VALIDATED">("DRAFT");
  const [toast,setToast] = useState("");
  const copy=getConsoleCopy(locale);
  const title=getViewTitle(locale,view);
  const visibleNavigation=navigation.filter((item)=>canAccessView(role,item.view));
  useEffect(()=>{
    const frame=window.requestAnimationFrame(()=>{
      const savedLocale=window.localStorage.getItem("advertest-locale");
      const savedTheme=window.localStorage.getItem("advertest-theme");
      if(savedLocale==="vi"||savedLocale==="en")setLocale(savedLocale);
      if(savedTheme==="dark"||savedTheme==="light")setTheme(savedTheme);
    });
    return()=>window.cancelAnimationFrame(frame);
  },[]);
  useEffect(()=>{document.documentElement.lang=locale},[locale]);
  useEffect(()=>{const sync=()=>setMobileReadOnly(window.innerWidth<720);sync();window.addEventListener("resize",sync);return()=>window.removeEventListener("resize",sync)},[]);
  useEffect(()=>{if(run.status!=="running"||run.progress>=100)return;const timer=window.setInterval(()=>setRun(current=>{const progress=Math.min(100,current.progress+1);return{...current,progress,cost:+(current.cost+.08).toFixed(2),cached:current.cached+9,status:progress===100?"complete":"running"}}),1200);return()=>window.clearInterval(timer)},[run.status,run.progress]);
  useEffect(()=>{
    const context=document.modelContext;if(!context?.registerTool)return;
    const lifecycle=new AbortController();
    const register=(tool:Parameters<typeof context.registerTool>[0])=>void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>undefined);
    register({name:"start_experiment_configuration",title:"Configure AdverTest experiment",description:"Open the visible experiment builder to configure a perception robustness benchmark.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:()=>{if(!permissions.canCreateExperiment(role))throw new Error("Test Engineer or Admin role required");setView("experiments");return{view:"experiments",status:"ready"}}});
    register({name:"start_adversarial_experiment",title:"Start adversarial experiment",description:"Start the configured deterministic AdverTest run and open its live monitor.",inputSchema:{type:"object",properties:{name:{type:"string"}},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:()=>{if(!permissions.canCreateExperiment(role))throw new Error("Test Engineer or Admin role required");setRun({progress:4,status:"running",cost:1.28,cached:82});setView("monitor");return{experimentId:"ADV-2026-091",status:"running"}}});
    register({name:"assign_failure_verdict",title:"Assign failure verdict",description:"Open the triage queue and stage a verdict for a perception failure case.",inputSchema:{type:"object",properties:{failureCaseId:{type:"string"},verdict:{type:"string"}},required:["failureCaseId","verdict"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input)=>{if(!permissions.canTriage(role))throw new Error("Safety Reviewer or Admin role required");setView("triage");return{...(input as object),status:"staged_for_review"}}});
    register({name:"sign_validated_report",title:"Sign validated report",description:"Sign the visible assurance report when the active role is Safety Reviewer or Admin.",inputSchema:{type:"object",properties:{reportId:{type:"string"}},required:["reportId"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input)=>{if(!permissions.canSignReport(role))throw new Error("Safety Reviewer or Admin role required");setReportStatus("VALIDATED");setView("reports");return{...(input as object),status:"VALIDATED"}}});
    return()=>lifecycle.abort();
  },[role]);
  const notify=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(""),2600)};
  const guardWrite=(action:()=>void)=>mobileReadOnly?notify("Mobile đang ở chế độ chỉ đọc"):action();
  const changeRole=(nextRole:Role)=>{setRole(nextRole);if(!canAccessView(nextRole,view))setView(firstAllowedView(nextRole))};
  const changeLocale=(nextLocale:Locale)=>{setLocale(nextLocale);window.localStorage.setItem("advertest-locale",nextLocale)};
  const changeTheme=(nextTheme:ConsoleTheme)=>{setTheme(nextTheme);window.localStorage.setItem("advertest-theme",nextTheme)};
  return <main className="app-shell" data-theme={theme}>
    <InteractiveBackground variant="console"/>
    <aside className="sidebar"><button className="brand" onClick={()=>setView("dashboard")}><span className="brand-mark"><ShieldCheck size={19}/></span><span><b>ADVER</b>TEST</span></button><nav className="nav-list" aria-label="Main navigation"><p className="nav-kicker">{copy.controlPlane}</p>{visibleNavigation.map(({view:target,icon:Icon,labelKey,count})=><button className={view===target?"nav-item is-active":"nav-item"} onClick={()=>setView(target)} key={target}><Icon size={17}/><span>{copy.nav[labelKey]}</span>{count&&<em>{count}</em>}</button>)}{permissions.canAdminister(role)&&<><p className="nav-kicker nav-kicker--spaced">{copy.system}</p><button className={view==="admin"?"nav-item is-active":"nav-item"} onClick={()=>setView("admin")}><Cpu size={17}/><span>{copy.nav.systemHub}</span></button></>}</nav><div className="sidebar-foot"><div className="quota-copy"><span>{copy.gpuMonth}</span><b>71%</b></div><div className="quota"><span/></div><small>142.8 / 200 A100-hours</small><div className="user-card"><span className="avatar">LN</span><span><b>Linh Nguyễn</b><small>{role}</small></span><UserRoundCheck size={16}/></div></div></aside>
    <section className="workspace"><header className="topbar"><div><p className="eyebrow">{title[1]} / 23.09.2026</p><h1>{title[0]}</h1></div><div className="top-actions"><label className="search"><Search size={16}/><input aria-label="Search" placeholder={copy.search}/><kbd>/</kbd></label>{permissions.canCreateExperiment(role)&&<button className="console-primary write-action" onClick={()=>guardWrite(()=>setView("experiments"))}><Plus size={16}/> {copy.create}</button>}<ConsoleToolbar locale={locale} theme={theme} role={role} onLocaleChange={changeLocale} onThemeChange={changeTheme} onRoleChange={changeRole} onLoadDemo={()=>notify(locale==="vi"?"Đã nạp bộ demo reproducible seed=42":"Loaded reproducible demo data with seed=42")}/></div></header><div className="alert-strip"><span><Activity size={16}/> <b>{copy.stable}</b> · {copy.workers}</span>{mobileReadOnly?<strong><Eye size={14}/> {copy.readOnly}</strong>:permissions.canAdminister(role)&&<button onClick={()=>setView("admin")}>{copy.resources} <ArrowUpRight size={14}/></button>}</div>
      <section className="content">{view==="dashboard"&&<Dashboard onView={(target)=>canAccessView(role,target)&&setView(target)}/>} {view==="experiments"&&<ExperimentBuilder locale={locale} onStart={()=>guardWrite(()=>{setRun({progress:4,status:"running",cost:1.28,cached:82});setView("monitor");notify(locale==="vi"?"Run ADV-2026-091 đã vào worker queue":"Run ADV-2026-091 entered the worker queue")})}/>} {view==="monitor"&&<RunMonitor run={run} canControl={permissions.canControlRun(role)} onPause={()=>guardWrite(()=>setRun(current=>({...current,status:current.status==="paused"?"running":"paused"})))} onCompare={()=>setView("compare")}/>} {view==="compare"&&<CompareView canTriage={permissions.canTriage(role)} onTriage={()=>guardWrite(()=>{notify("FC-039 đã được gửi vào Triage");setView("triage")})}/>} {view==="matrix"&&<MatrixView onInspect={()=>setView("compare")}/>} {view==="triage"&&<TriageView role={role} onSave={()=>guardWrite(()=>notify("Verdict đã lưu; chuyển sang case tiếp theo"))}/>} {view==="reports"&&<ReportView role={role} status={reportStatus} onSign={()=>guardWrite(()=>{if(!permissions.canSignReport(role))return notify("Chỉ Safety Reviewer hoặc Admin được ký");setReportStatus("VALIDATED");notify("Báo cáo đã được ký và khóa audit trail")})}/>} {view==="admin"&&<AdminView role={role} onChange={()=>guardWrite(()=>notify("Registry đã cập nhật"))}/>}</section>
    </section>{toast&&<div className="toast"><CheckCircle2 size={16}/>{toast}</div>}{permissions.canCreateExperiment(role)&&<button className="mobile-run" onClick={()=>setView("experiments")}><Plus size={18}/> {copy.builder}</button>}
  </main>;
}

function Dashboard({onView}:{onView:(view:View)=>void}) {
  return <><SectionTitle index="01" title="Tình hình hôm nay" detail="12 thí nghiệm trong 30 ngày · cập nhật 18 giây trước"/><div className="metrics-grid"><MetricCard label="CLEAN mAP" value="72.8" detail="YOLOv8n · KITTI val" tone="green"/><MetricCard label="MEAN PERFORMANCE" value="49.6" detail="mPC · 15 corruptions" tone="cyan"/><MetricCard label="ROBUST RETENTION" value="68.1%" detail="rPC · giảm 4.2 điểm" tone="orange"/><MetricCard label="FAILURE CASES" value="38" detail="12 case chưa review" tone="red"/></div><div className="dashboard-grid"><article className="panel panel--chart"><div className="panel-head"><div><p>PERFORMANCE DECAY</p><h3>Đường cong robustness</h3></div><div className="legend"><span><i className="legend-map"/> mAP</span><span><i className="legend-retention"/> Retention</span></div></div><RobustnessChart/><div className="breaking-point"><Gauge size={16}/><span>Breaking point tại <b>Severity 4</b></span><small>mAP giảm dưới ngưỡng an toàn 45.0</small></div></article><article className="panel risk-panel"><div className="panel-head"><div><p>RISK SIGNAL</p><h3>Cần xử lý</h3></div><button className="icon-button" onClick={()=>onView("triage")}><ArrowUpRight size={17}/></button></div><div className="risk-score"><span>RISK<br/>INDEX</span><strong>74</strong><em>/100</em></div><div className="risk-list"><RiskItem tone="red" icon={<AlertTriangle size={15}/>} title="12 case nghiêm trọng" sub="Pedestrian disappearance" tag="HIGH"/><RiskItem tone="orange" icon={<CircleDollarSign size={15}/>} title="Budget vượt dự báo 8%" sub="PGD sweep · 2 run" tag="WATCH"/><RiskItem tone="cyan" icon={<Database size={15}/>} title="COCO split lệch lớp" sub="Cyclist mapping chưa đủ" tag="CHECK"/></div></article></div><SectionTitle index="02" title="Run gần đây" action={<button className="text-button" onClick={()=>onView("experiments")}>Xem tất cả <ChevronRight size={15}/></button>}/><div className="run-table"><div className="run-row run-row--head"><span>THÍ NGHIỆM</span><span>TRẠNG THÁI</span><span>TIẾN ĐỘ</span><span>TÍN HIỆU</span><span/></div>{experimentRows.map((experiment,index)=><div className="run-row" key={experiment.name}><span className="experiment-name"><i>0{index+1}</i><b>{experiment.name}</b><small>{index===0?"fog · snow · frost · severity 1-5":index===1?"untargeted · epsilon 8/255 · 40 steps":"defocus · motion · glass blur"}</small></span><span><mark className={`status status--${experiment.tone}`}><i/>{experiment.status}</mark></span><span className="progress-cell"><span><i style={{width:`${experiment.progress}%`}}/></span><b>{experiment.progress}%</b></span><span className="delta">{experiment.delta}</span><span><button className="row-button" onClick={()=>onView(index===0?"monitor":"matrix")}>Mở <ChevronRight size={14}/></button></span></div>)}</div></>;
}
function RobustnessChart(){return <div className="chart-wrap"><ResponsiveContainer width="100%" height="100%" minWidth={0} minHeight={0}><AreaChart data={robustness} margin={{top:8,right:12,left:-20,bottom:0}}><defs><linearGradient id="cyanArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#37d8f5" stopOpacity={.24}/><stop offset="100%" stopColor="#37d8f5" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#26323c" strokeDasharray="3 5" vertical={false}/><XAxis dataKey="severity" stroke="#71808d" tickLine={false} axisLine={false} fontSize={11}/><YAxis stroke="#71808d" tickLine={false} axisLine={false} fontSize={11}/><Tooltip contentStyle={{background:"#101820",border:"1px solid #34434f",color:"#f6f0e3",borderRadius:8}}/><Area type="monotone" dataKey="map" stroke="#37d8f5" strokeWidth={2.5} fill="url(#cyanArea)"/><Line type="monotone" dataKey="retention" stroke="#ff7a45" strokeWidth={2} dot={{r:3,fill:"#ff7a45"}}/></AreaChart></ResponsiveContainer></div>}
function RiskItem({tone,icon,title,sub,tag}:{tone:string;icon:React.ReactNode;title:string;sub:string;tag:string}){return <div><span className={`risk-icon risk-icon--${tone}`}>{icon}</span><p><b>{title}</b><small>{sub}</small></p><em>{tag}</em></div>}

function RunMonitor({run,onPause,onCompare,canControl}:{run:RunState;onPause:()=>void;onCompare:()=>void;canControl:boolean}) {
  return <><div className="monitor-hero"><div><mark className={`status status--${run.status==="complete"?"green":"cyan"}`}><i/>{run.status.toUpperCase()}</mark><h2>ADV-2026-091 · KITTI Weather Sweep</h2><p>YOLOv8n · KITTI val · 90 variants · worker gpu-a100-03</p></div><div className="monitor-actions">{canControl&&<button className="button button--ghost write-action" onClick={onPause}>{run.status==="paused"?<Play size={15}/>:<Pause size={15}/>} {run.status==="paused"?"Tiếp tục":"Tạm dừng"}</button>}<button className="button button--primary" onClick={onCompare}>Mở compare</button></div></div><div className="monitor-progress"><div className="ring" style={{"--progress":`${run.progress*3.6}deg`} as React.CSSProperties}><span><b>{run.progress}%</b><small>COMPLETE</small></span></div><div className="stage-list">{[["01","Clean baseline",100],["02","Corruption sweep",run.progress],["03","Gradient attacks",Math.max(0,run.progress-42)],["04","Aggregate & report",run.progress===100?100:0]].map(([number,label,progress])=><div key={label as string}><span>{number}</span><p><b>{label}</b><small>{progress}% · {progress===100?"done":progress?"processing":"waiting"}</small></p><div><i style={{width:`${progress}%`}}/></div></div>)}</div><div className="live-stats"><MetricCard label="GPU COST" value={`$${run.cost.toFixed(2)}`} detail="hard cap $48" tone="orange"/><MetricCard label="CACHE HITS" value={run.cached.toLocaleString("vi-VN")} detail="31% saved" tone="cyan"/><MetricCard label="ETA" value={run.status==="complete"?"DONE":"18m"} detail="finish ~20:46" tone="green"/></div></div><div className="monitor-grid"><article className="panel log-panel"><div className="panel-head"><div><p>WORKER EVENTS</p><h3>Live event stream</h3></div><span className="live-pill">LIVE</span></div>{["20:28:41 · severity=4 snow · batch 188/250 · mAP=40.2","20:28:37 · failure FC-038 · pedestrian disappearance","20:28:31 · cache hit clean/predictions · 200 samples","20:28:24 · checkpoint saved · spec_hash=8f2a91"].map(line=><code key={line}>{line}</code>)}</article><article className="panel"><div className="panel-head"><div><p>EARLY SIGNAL</p><h3>Metric hiện tại</h3></div></div><RobustnessChart/></article></div></>;
}

function CompareView({onTriage,canTriage}:{onTriage:()=>void;canTriage:boolean}) {
  const [severity,setSeverity]=useState(4);const [overlay,setOverlay]=useState(true);const [sample,setSample]=useState(7481);
  return <><div className="failure-banner"><AlertTriangle size={17}/><span><b>FAILURE CASE</b> · Pedestrian disappearance at Snow / Severity {severity}</span>{canTriage&&<button className="button button--primary write-action" onClick={onTriage}>Gửi Triage</button>}</div><div className="compare-toolbar"><button onClick={()=>setSample(v=>v-1)}><ArrowLeft size={15}/></button><b>KITTI-{String(sample).padStart(6,"0")}</b><button onClick={()=>setSample(v=>v+1)}><ArrowRight size={15}/></button><label>Severity <input type="range" min="1" max="5" value={severity} onChange={e=>setSeverity(+e.target.value)}/><b>S{severity}</b></label><label className="toggle"><input type="checkbox" checked={overlay} onChange={e=>setOverlay(e.target.checked)}/><span/> Perturbation overlay</label></div><div className="scene-grid"><Scene title="CLEAN / GROUND TRUTH" attacked={false} overlay={false}/><Scene title={`ATTACKED / SNOW S${severity}`} attacked overlay={overlay}/></div><div className="sample-metrics"><MetricCard label="CONFIDENCE" value="0.91 → 0.18" detail="pedestrian · -80.2%" tone="red"/><MetricCard label="BOX IoU" value="0.84 → 0.11" detail="disappearance threshold" tone="orange"/><MetricCard label="PREDICTION" value="Person → ∅" detail="critical safety object" tone="red"/><MetricCard label="PERTURBATION" value="14.2 dB" detail="weather visibility" tone="cyan"/></div></>;
}
function Scene({title,attacked,overlay}:{title:string;attacked:boolean;overlay:boolean}) {return <figure className={`scene ${attacked?"scene--attacked":""} ${overlay?"scene--overlay":""}`}><figcaption>{title}<span>{attacked?"mAP 40.2":"mAP 72.8"}</span></figcaption><div className="sky"><i className="mountain mountain--one"/><i className="mountain mountain--two"/></div><div className="road"><span className="lane lane--one"/><span className="lane lane--two"/><span className="car car--one"/><span className="car car--two"/><span className="person"/></div><span className="bbox bbox--car">car · 0.94</span><span className="bbox bbox--car2">car · 0.88</span>{!attacked&&<span className="bbox bbox--person">person · 0.91</span>}{attacked&&<span className="missed">MISSED GT</span>}{overlay&&<div className="snow">{Array.from({length:45},(_,index)=><i key={index} style={{left:`${(index*37)%100}%`,top:`${(index*61)%100}%`}}/>)}</div>}</figure>}

function MatrixView({onInspect}:{onInspect:()=>void}) {const [compare,setCompare]=useState(false);return <><div className="matrix-toolbar"><div><b>YOLOv8n · KITTI-C</b><small>mAP50 by corruption / severity</small></div><label className="toggle"><input type="checkbox" checked={compare} onChange={e=>setCompare(e.target.checked)}/><span/> So sánh YOLOv8m</label><button className="button button--ghost">Xuất CSV</button></div><div className={compare?"matrix-pair":""}><RobustnessMatrix title="YOLOv8n" onInspect={onInspect}/>{compare&&<RobustnessMatrix title="YOLOv8m" onInspect={onInspect} stronger/>}</div><SectionTitle index="02" title="Top-K failures" detail="Xếp hạng theo severity_score × safety criticality"/><div className="topk-grid">{initialCases.map((item,index)=><button onClick={onInspect} className="failure-card" key={item.id}><span className="rank">0{index+1}</span><div><b>{item.issue}</b><small>{item.sample} · {item.attack}</small></div><strong>{[96,91,87,72][index]}</strong><ChevronRight size={15}/></button>)}</div></>}
function RobustnessMatrix({title,onInspect,stronger=false}:{title:string;onInspect:()=>void;stronger?:boolean}) {return <article className="matrix-panel"><div className="matrix-head"><h3>{title}</h3><span>Clean <b>{stronger?"76.4":"72.8"}</b></span><span>mPC <b>{stronger?"55.1":"49.6"}</b></span><span>rPC <b>{stronger?"72.1%":"68.1%"}</b></span></div><div className="matrix-table"><div className="matrix-row matrix-row--head"><span>CORRUPTION</span>{[1,2,3,4,5].map(level=><span key={level}>S{level}</span>)}<span>BREAK</span></div>{corruptionRows.map(([name,...values])=><div className="matrix-row" key={name}><b>{name}</b>{values.map((value,index)=>{const adjusted=stronger?Math.min(78,value+5):value;return <button onClick={onInspect} key={index} style={{"--heat":`${Math.max(12,adjusted)}%`} as React.CSSProperties}>{adjusted}</button>})}<em>{values.findIndex(value=>value<45)+1||">5"}</em></div>)}</div></article>}

function TriageView({role,onSave}:{role:Role;onSave:()=>void}) {const [selected,setSelected]=useState(0);const [verdict,setVerdict]=useState("Confirmed");const item=initialCases[selected];return <div className="triage-layout"><section><div className="queue-head"><div><p>12 / 38 chưa review</p><div><i style={{width:"68%"}}/></div></div><button className="button button--ghost write-action">Gán hàng loạt</button></div><div className="case-list">{initialCases.map((entry,index)=><button className={selected===index?"case-row is-selected":"case-row"} onClick={()=>setSelected(index)} key={entry.id}><span><b>{entry.id}</b><small>{entry.sample}</small></span><span><b>{entry.issue}</b><small>{entry.attack}</small></span><mark className={`severity severity--${entry.severity.toLowerCase()}`}>{entry.severity}</mark><ChevronRight size={15}/></button>)}</div></section><aside className="review-panel"><div className="review-title"><span><ShieldCheck size={17}/></span><div><p>CASE REVIEW</p><h3>{item.id} · {item.sample}</h3></div></div><Scene title="ATTACKED SAMPLE" attacked overlay/><div className="review-form"><label>VERDICT<div className="verdicts">{["Confirmed","Expected","False positive","Needs data"].map(value=><button onClick={()=>setVerdict(value)} className={verdict===value?"is-selected":""} key={value}>{value}</button>)}</div></label><label>MITIGATION<select><option>Weather augmentation + fine-tune</option><option>Confidence calibration</option><option>Sensor fusion fallback</option><option>Dataset expansion</option></select></label><label>REVIEW NOTE<textarea defaultValue="Failure tái lập với seed 42. Pedestrian bị mất hoàn toàn từ S4; cần thêm snow augmentation và kiểm tra fusion LiDAR."/></label><div className="review-meta"><span>Reviewer role</span><b>{role}</b></div><button className="button button--primary button--block write-action" onClick={onSave}>Lưu & case tiếp <ArrowRight size={15}/></button><small>Phím tắt: 1-4 verdict · J/K chuyển case · Space lưu</small></div></aside></div>}

function ReportView({role,status,onSign}:{role:Role;status:"DRAFT"|"VALIDATED";onSign:()=>void}) {const checks=["Run hoàn tất và config hash hợp lệ","38/38 failure case đã có verdict","Top-K critical có mitigation","Budget không vượt hard cap","Artifact dùng dữ liệu đã ẩn danh"];return <><div className={`report-banner report-banner--${status.toLowerCase()}`}><div><LockKeyhole size={20}/><span><b>{status}</b><small>{status==="DRAFT"?"Chưa được dùng cho quyết định release":"Đã khóa · đủ điều kiện assurance review"}</small></span></div><span className="watermark">{status}</span></div><div className="report-grid"><article className="paper-report"><header><span className="brand-mark"><ShieldCheck size={18}/></span><div><p>ADVERTEST ASSURANCE REPORT</p><h2>KITTI Weather + Adversarial Sweep</h2></div><em>RPT-2026-091</em></header><div className="report-summary"><MetricCard label="CLEAN mAP" value="72.8" detail="baseline" tone="green"/><MetricCard label="mPC" value="49.6" detail="mean corruption" tone="orange"/><MetricCard label="rPC" value="68.1%" detail="retention" tone="cyan"/></div><h3>Executive finding</h3><p>Mô hình không đạt ngưỡng release cho điều kiện tuyết severity 4-5. Phát hiện 12 failure case critical liên quan pedestrian; khuyến nghị weather augmentation, calibration và kiểm thử lại trước release.</p><h3>Benchmark coverage</h3><div className="coverage"><span>15 corruptions × 5 severity</span><span>FGSM · PGD · MI-FGSM · C&W</span><span>7,481 KITTI images</span><span>seed 42 · deterministic</span></div><h3>Audit signatures</h3><div className="signature"><span>Prepared by</span><b>Minh Trần · Test Engineer</b><small>23 Sep 2026 · SHA 8f2a91</small></div>{status==="VALIDATED"&&<div className="signature signature--valid"><span>Validated by</span><b>Linh Nguyễn · Safety Reviewer</b><small>23 Sep 2026 · immutable audit event #418</small></div>}</article><aside className="signoff-panel"><p>RELEASE GATE</p><h3>Checklist sign-off</h3>{checks.map(check=><div className="gate-check" key={check}><CheckCircle2 size={16}/><span>{check}</span></div>)}<div className="role-gate"><span>Vai trò hiện tại</span><b>{role}</b><small>{role==="Test Engineer"?"Không có quyền ký báo cáo":"Đủ quyền ký assurance gate"}</small></div><button disabled={status==="VALIDATED"||role==="Test Engineer"} className="button button--primary button--block write-action" onClick={onSign}><ShieldCheck size={16}/>{status==="VALIDATED"?"Đã ký & khóa":"Ký VALIDATED"}</button><button className="button button--ghost button--block">Xuất PDF bundle</button><p className="export-note"><LockKeyhole size={13}/> Export không chứa ảnh gốc hoặc PII; chỉ artifact đã ẩn danh.</p><div className="audit-mini"><b><History size={14}/> Audit log</b><small>20:41 · Reviewer opened report</small><small>20:36 · Triage completed 38/38</small><small>20:32 · Report generated</small></div></aside></div></>}

function AdminView({role,onChange}:{role:Role;onChange:()=>void}) {return <><div className="admin-warning"><LockKeyhole size={16}/><span>{role==="Admin"?"Admin write access enabled":"Bạn đang xem cấu hình ở chế độ read-only; chuyển role Admin để chỉnh sửa."}</span></div><SectionTitle index="01" title="GPU pool & quota" detail="A100 cluster · cost controls"/><div className="resource-grid">{[["gpu-a100-01","RUNNING","92%","ADV-089"],["gpu-a100-02","IDLE","0%","—"],["gpu-a100-03","RUNNING","78%","ADV-091"],["gpu-a100-04","OFFLINE","—","maintenance"]].map(([name,state,load,job])=><article className="resource-card" key={name}><Cpu size={20}/><div><b>{name}</b><small>{job}</small></div><span>{load}</span><mark className={`status status--${state==="RUNNING"?"cyan":state==="IDLE"?"green":"orange"}`}><i/>{state}</mark></article>)}</div><SectionTitle index="02" title="Model registry" detail="Signed weights · adapter compatibility"/><div className="registry-table"><div className="registry-row registry-row--head"><span>MODEL</span><span>FRAMEWORK</span><span>DATASET</span><span>SIGNATURE</span><span>STATUS</span><span/></div>{[["YOLOv8n","Ultralytics 8.2","COCO → KITTI","sha256:bc18...","Active"],["YOLOv8m","Ultralytics 8.2","COCO","sha256:2f91...","Active"],["Faster R-CNN","MMDetection 3.3","Cityscapes","sha256:91aa...","Review"],["SAM2-small","Meta SAM2","COCO","sha256:c731...","Adapter beta"]].map(row=><div className="registry-row" key={row[0]}>{row.map(cell=><span key={cell}>{cell}</span>)}<button onClick={onChange} disabled={role!=="Admin"}>Sửa</button></div>)}</div></>}
